# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
book = Book.create(title: "The Hobbit", author: "J.R.R. Tolkien", description: "The Hobbit, or There and Back Again is a children's fantasy novel written by English author J. R. R. Tolkien. It is the first of three volumes in The Hobbit, following The Desolation of Smaug. The story is set in the fantasy world of Middle-earth, in which the hobbit Bilbo Baggins has an uneventful life. The hobbit is a simple Hobbit, who is content with his comfortable life in the shire, and who does not feel any kinship with the great dragon Smaug. Bilbo's quest for the One Ring begins.", image: "https://images-na.ssl-images-amazon.com/images/I/51-%2Bq-%2B%2BqL._SX331_BO1,204,203,200_.jpg", category: "Fiction", total_pages: "320", daily_pages_reading: "10");

book = Book.create(title: "The Lord of the Rings", author: "J.R.R. Tolkien", description: "The Lord of the Rings is an epic high-fantasy novel written by English author J. R. R. Tolkien. The story began as a sequel to The Hobbit, but eventually developed into a much larger work. It is one of the best-selling novels in the English language, with over 150 million copies sold, and has been translated into many languages. The story began as a sequel to The Hobbit, but eventually developed into a much larger work. It is one of the best-selling novels in the English language, with over 150 million copies sold, and has been translated into many languages.", image: "https://images-na.ssl-images-amazon.com/images/I/51-%2Bq-%2B%2BqL._SX331_BO1,204,203,200_.jpg", category: "Fiction",  total_pages: "320", daily_pages_reading: "10")

book = Book.create(title: "Moby-Dick; or, The Whale", author: "Herman Melville.", description: "The Hobbit, or There and Back Again is a children's fantasy novel written by English author J. R. R. Tolkien. It is the first of three volumes in The Hobbit, following The Desolation of Smaug. The story is set in the fantasy world of Middle-earth, in which the hobbit Bilbo Baggins has an uneventful life. The hobbit is a simple Hobbit, who is content with his comfortable life in the shire, and who does not feel any kinship with the great dragon Smaug. Bilbo's quest for the One Ring begins.", image: "https://images-na.ssl-images-amazon.com/images/I/51-%2Bq-%2B%2BqL._SX331_BO1,204,203,200_.jpg",  category: "Fiction", total_pages: "320", daily_pages_reading: "10" )
book = Book.create(title: "The Lord of the Rings", author: "J.R.R. Tolkien", description: "The Lord of the Rings is an epic high-fantasy novel written by English author J. R. R. Tolkien. The story began as a sequel to The Hobbit, but eventually developed into a much larger work. It is one of the best-selling novels in the English language, with over 150 million copies sold, and has been translated into many languages. The story began as a sequel to The Hobbit, but eventually developed into a much larger work. It is one of the best-selling novels in the English language, with over 150 million copies sold, and has been translated into many languages.", image: "https://images-na.ssl-images-amazon.com/images/I/51-%2Bq-%2B%2BqL._SX331_BO1,204,203,200_.jpg", category: "Fiction", total_pages: "320", daily_pages_reading: "10");

book = Book.create(title: "The Hobbit", author: "J.R.R. Tolkien", description: "The Hobbit, or There and Back Again is a children's fantasy novel written by English author J. R. R. Tolkien. It is the first of three volumes in The Hobbit, following The Desolation of Smaug. The story is set in the fantasy world of Middle-earth, in which the hobbit Bilbo Baggins has an uneventful life. The hobbit is a simple Hobbit, who is content with his comfortable life in the shire, and who does not feel any kinship with the great dragon Smaug. Bilbo's quest for the One Ring begins.", image: "https://images-na.ssl-images-amazon.com/images/I/51-%2Bq-%2B%2BqL._SX331_BO1,204,203,200_.jpg", category: "Fiction", total_pages: "320", daily_pages_reading: "10");

book = Book.create(title: "The Lord of the Rings", author: "J.R.R. Tolkien", description: "The Lord of the Rings is an epic high-fantasy novel written by English author J. R. R. Tolkien. The story began as a sequel to The Hobbit, but eventually developed into a much larger work. It is one of the best-selling novels in the English language, with over 500 million copies sold, and has been translated into many languages. The story began as a sequel to The Hobbit, but eventually developed into a much larger work. It is one of the best-selling novels in the English language, with over 500 million copies sold, and has been translated into many languages.", image: "https://images-na.ssl-images-amazon.com/images/I/51-%2Bq-%2B%2BqL._SX331_BO1,204,203,200_.jpg", category: "Fiction", total_pages: "320", daily_pages_reading: "10");



book = Book.create(title: "Moby-Dick", author: "Herman Melville.", description: "The Hobbit, or There and Back Again is a children's fantasy novel written by English author J. R. R. Tolkien. It is the first of three volumes in The Hobbit, following The Desolation of Smaug. The story is set in the fantasy world of Middle-earth, in which the hobbit Bilbo Baggins has an uneventful life. The hobbit is a simple Hobbit, who is content with his comfortable life in the shire, and who does not feel any kinship with the great dragon Smaug. Bilbo's quest for the One Ring begins.", image: "https://images-na.ssl-images-amazon.com/images/I/51-%2Bq-%2B%2BqL._SX331_BO1,204,203,200_.jpg", category: "Fiction", total_pages: "320", daily_pages_reading: "20")

book = Book.create(title: "The Lord of the Rings", author: "J.R.R. Tolkien", description: "The Lord of the Rings is an epic high-fantasy novel written by English author J. R. R. Tolkien. The story began as a sequel to The Hobbit, but eventually developed into a much larger work. It is one of the best-selling novels in the English language, with over 500 million copies sold, and has been translated into many languages. The story began as a sequel to The Hobbit, but eventually developed into a much larger work. It is one of the best-selling novels in the English language, with over 500 million copies sold, and has been translated into many languages.", image: "https://images-na.ssl-images-amazon.com/images/I/51-%2Bq-%2B%2BqL._SX331_BO1,204,203,200_.jpg",  category: "Fiction", total_pages: "320", daily_pages_reading: "6");

book = Book.create(title: "Catch-22" , author: "Joseph Heller", description: " A novel seven years in the making (published in 1961) and said to be one of the most important in the 20th century. Catch-22 primarily follows the storyline of Captain John Yossarian, a crewman of a World War II bomber who is stationed on a small Mediterranean island where he repeatedly, and desperately, attempts to stay alive.", image: "https://images-na.ssl-images-amazon.com/images/I/51lPwHudz0L._SY291_BO1,204,203,200_QL40_FMwebp_.jpg", category: "Fiction", total_pages: "320", daily_pages_reading: "4");

book = Book.create(title: "The Great Gatsby", author: "F. Scott Fitzgerald", description: "Set among the rich of 1920’s New York City, the mysterious millionaire Jay Gatsby pursues his quixotic passion and obsession for the former debutante Daisy Buchanan.", image: "https://images-na.ssl-images-amazon.com/images/I/51sd9MSi72L._SX373_BO1,204,203,200_.jpg", category: "Fiction", total_pages: "320", daily_pages_reading: "5");

