# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
book = Book.create(title: "The Hobbit", author: "J.R.R. Tolkien", description: "The Hobbit, or There and Back Again is a children's fantasy novel written by English author J. R. R. Tolkien. It is the first of three volumes in The Hobbit, following The Desolation of Smaug. The story is set in the fantasy world of Middle-earth, in which the hobbit Bilbo Baggins has an uneventful life. The hobbit is a simple Hobbit, who is content with his comfortable life in the shire, and who does not feel any kinship with the great dragon Smaug. Bilbo's quest for the One Ring begins.", image: "https://upload.wikimedia.org/wikipedia/en/a/a9/The_Hobbit_trilogy_dvd_cover.jpg", category: "Fiction", total_pages: "320", daily_pages_reading: "10");

book = Book.create(title: "The Lord of the Rings", author: "J.R.R. Tolkien", description: "The Lord of the Rings is an epic high-fantasy novel written by English author J. R. R. Tolkien. The story began as a sequel to The Hobbit, but eventually developed into a much larger work. It is one of the best-selling novels in the English language, with over 150 million copies sold, and has been translated into many languages. The story began as a sequel to The Hobbit, but eventually developed into a much larger work. It is one of the best-selling novels in the English language, with over 150 million copies sold, and has been translated into many languages.", image: "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_.jpg", category: "Fiction",  total_pages: "320", daily_pages_reading: "10")

book = Book.create(title: "Moby-Dick or The Whale", author: "Herman Melville.", description: "The Hobbit, or There and Back Again is a children's fantasy novel written by English author J. R. R. Tolkien. It is the first of three volumes in The Hobbit, following The Desolation of Smaug. The story is set in the fantasy world of Middle-earth, in which the hobbit Bilbo Baggins has an uneventful life. The hobbit is a simple Hobbit, who is content with his comfortable life in the shire, and who does not feel any kinship with the great dragon Smaug. Bilbo's quest for the One Ring begins.", image: "https://preview.redd.it/nxuisj0puaf21.jpg?auto=webp&s=c7fc9339359196fcc7cae3ed2a89b462f651e97e",  category: "Fiction", total_pages: "320", daily_pages_reading: "10" )
book = Book.create(title: "In Search of Lost Time ", author: "Marcel Proust", description: "Swann's Way, the first part of A la recherche de temps perdu, Marcel Proust's seven-part cycle, was published in 1913. In it, Proust introduces the themes that run through the entire work. The narrator recalls his childhood, aided by the famous madeleine; and describes M. Swann's passion for Odette. The work is incomparable. Edmund Wilson said [Proust] has supplied for the first time in literature an equivalent in the full scale for the new theory of modern physics.", image: "https://d3i5mgdwi2ze58.cloudfront.net/7hqv6ddaqv363p4hadx6lymotow1", category: "Fiction", total_pages: "320", daily_pages_reading: "10");

book = Book.create(title: "Ulysses", author: "James Joyce", description: "Ulysses chronicles the passage of Leopold Bloom through Dublin during an ordinary day, June 16, 1904. The title parallels and alludes to Odysseus (Latinised into Ulysses), the hero of Homer's Odyssey (e.g., the correspondences between Leopold Bloom and Odysseus, Molly Bloom and Penelope, and Stephen Dedalus and Telemachus). Joyce fans worldwide now celebrate June 16 as Bloomsday.", image: "https://d3i5mgdwi2ze58.cloudfront.net/usuab7s8yuwlcmadwx9woy746lvi", category: "Fiction", total_pages: "320", daily_pages_reading: "10");

book = Book.create(title: "Don Quixote", author: "Miguel de Cervantes", description: "Alonso Quixano, a retired country gentleman in his fifties, lives in an unnamed section of La Mancha with his niece and a housekeeper. He has become obsessed with books of chivalry, and believes their every word to be true, despite the fact that many of the events in them are clearly impossible. Quixano eventually appears to other people to have lost his mind from little sleep and food and because of so much reading.", image: "https://d3i5mgdwi2ze58.cloudfront.net/mhm76qp1y0vi165f1h7ea0b0lps5", category: "Fiction", total_pages: "320", daily_pages_reading: "10");
